workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods
          pod install
      - name: Set up keychain
        script: |
          security create-keychain -p "" build.keychain
          security import ./certs/dist.cer -k build.keychain -T /usr/bin/codesign
          security import ./certs/key.p12 -k build.keychain -P "password" -T /usr/bin/codesign
          security list-keychains -d user -s build.keychain
          security default-keychain -d user -s build.keychain
          security unlock-keychain -p "" build.keychain
      - name: Build IPA
        script: |
          xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -sdk iphoneos -configuration Release archive -archivePath $PWD/build/MyApp.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/MyApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build
    artifacts:
      - build/MyApp.ipa
      - build/MyApp.xcarchive
